# Generated by Django 5.1.5 on 2025-02-03 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FileModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('file', models.FileField(upload_to='uploads/')),
                ('file_type', models.CharField(max_length=50)),
                ('file_size', models.PositiveBigIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_retrieved_at', models.DateTimeField(blank=True, null=True)),
                ('alt_text', models.TextField(blank=True, null=True)),
                ('retrieval_count', models.PositiveIntegerField(default=0)),
            ],
        ),
    ]
