# Generated by Django 5.1.5 on 2025-02-03 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filemodel',
            name='alt_text',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='filemodel',
            name='file_size',
            field=models.PositiveBigIntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='filemodel',
            name='file_type',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
