# Generated by Django 5.1.5 on 2025-02-03 23:03

import files.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0002_alter_filemodel_alt_text_alter_filemodel_file_size_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='filemodel',
            name='file_extension',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='filemodel',
            name='stored_as',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='filemodel',
            name='alt_text',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='filemodel',
            name='file',
            field=models.FileField(upload_to=files.models.file_upload_to),
        ),
    ]
