# Generated by Django 5.1.5 on 2025-02-04 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0003_filemodel_file_extension_filemodel_stored_as_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filemodel',
            name='alt_text',
            field=models.TextField(),
        ),
    ]
