# Generated by Django 5.1.5 on 2025-02-07 17:14

import files.models
import storages.backends.s3
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0004_alter_filemodel_alt_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filemodel',
            name='file',
            field=models.FileField(storage=storages.backends.s3.S3Storage(), upload_to=files.models.file_upload_to),
        ),
    ]
