# Generated by Django 5.1.5 on 2025-02-09 14:43

import files.models
import storages.backends.s3
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0005_alter_filemodel_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='filemodel',
            name='optimized_image',
            field=models.ImageField(blank=True, null=True, storage=storages.backends.s3.S3Storage(), upload_to=files.models.file_upload_to),
        ),
        migrations.AddField(
            model_name='filemodel',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, storage=storages.backends.s3.S3Storage(), upload_to=files.models.file_upload_to),
        ),
    ]
