# Generated by Django 5.1.5 on 2025-02-09 17:00

import storages.backends.s3
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0006_filemodel_optimized_image_filemodel_thumbnail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filemodel',
            name='file',
            field=models.FileField(storage=storages.backends.s3.S3Storage(), upload_to=''),
        ),
        migrations.AlterField(
            model_name='filemodel',
            name='optimized_image',
            field=models.ImageField(blank=True, null=True, storage=storages.backends.s3.S3Storage(), upload_to=''),
        ),
        migrations.AlterField(
            model_name='filemodel',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, storage=storages.backends.s3.S3Storage(), upload_to=''),
        ),
    ]
